#!/bin/bash

PYTHON_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')

SUPPORTED_VERSIONS=("3.12" "3.13")

if [[ ! " ${SUPPORTED_VERSIONS[@]} " =~ " ${PYTHON_VERSION} " ]]; then
    echo "Error: Python version $PYTHON_VERSION is not supported."
    exit 1
fi

BASE_FEED=http://feed.tv-lounge.eu/mediastream

if [ -e "$D/etc/opkg/mediastream-feed.conf" ]; then
    rm "$D/etc/opkg/mediastream-feed.conf" >/dev/null 2>&1 || true
fi

echo "src/gz mediastream-feed $BASE_FEED/$PYTHON_VERSION" > "$D/etc/opkg/mediastream-feed.conf"

opkg update
echo "Mediastream Feed successfully installed ..."
exit 0
